version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
- dotnet restore
- dotnet --version
before_build: 
- appveyor-retry dotnet restore -v Minimal
build_script: 
- dotnet build
test_script:
- cd BibleUtilities.Test
- dotnet xunit
- cd ..
cache:
- '%USERPROFILE%\.nuget\packages'
deploy:
- provider: NuGet
  api_key:
    secure: kF64utGBsftd5I68NZ5fp6gU8e2h8+z9O0ISOrCMDfa0Mh8Y9gwycA4Y+KHoV52K
  artifact: /.*\.nupkg/