//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHaven.BibleUtilities.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Books {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Books() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DHaven.BibleUtilities.Resources.Books", typeof(Books).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acts.
        /// </summary>
        internal static string Acts {
            get {
                return ResourceManager.GetString("Acts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amos.
        /// </summary>
        internal static string Amos {
            get {
                return ResourceManager.GetString("Amos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colossians.
        /// </summary>
        internal static string Colossians {
            get {
                return ResourceManager.GetString("Colossians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daniel.
        /// </summary>
        internal static string Daniel {
            get {
                return ResourceManager.GetString("Daniel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuteronomy.
        /// </summary>
        internal static string Deuteronomy {
            get {
                return ResourceManager.GetString("Deuteronomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecclesiastes.
        /// </summary>
        internal static string Ecclesiastes {
            get {
                return ResourceManager.GetString("Ecclesiastes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ephesians.
        /// </summary>
        internal static string Ephesians {
            get {
                return ResourceManager.GetString("Ephesians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esther.
        /// </summary>
        internal static string Esther {
            get {
                return ResourceManager.GetString("Esther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exodus.
        /// </summary>
        internal static string Exodus {
            get {
                return ResourceManager.GetString("Exodus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezekiel.
        /// </summary>
        internal static string Ezekiel {
            get {
                return ResourceManager.GetString("Ezekiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezra.
        /// </summary>
        internal static string Ezra {
            get {
                return ResourceManager.GetString("Ezra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth.
        /// </summary>
        internal static string Fifth {
            get {
                return ResourceManager.GetString("Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        internal static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galatians.
        /// </summary>
        internal static string Galatians {
            get {
                return ResourceManager.GetString("Galatians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genesis.
        /// </summary>
        internal static string Genesis {
            get {
                return ResourceManager.GetString("Genesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habakkuk.
        /// </summary>
        internal static string Habakkuk {
            get {
                return ResourceManager.GetString("Habakkuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haggai.
        /// </summary>
        internal static string Haggai {
            get {
                return ResourceManager.GetString("Haggai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrews.
        /// </summary>
        internal static string Hebrews {
            get {
                return ResourceManager.GetString("Hebrews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosea.
        /// </summary>
        internal static string Hosea {
            get {
                return ResourceManager.GetString("Hosea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isaiah.
        /// </summary>
        internal static string Isaiah {
            get {
                return ResourceManager.GetString("Isaiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James.
        /// </summary>
        internal static string James {
            get {
                return ResourceManager.GetString("James", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeremiah.
        /// </summary>
        internal static string Jeremiah {
            get {
                return ResourceManager.GetString("Jeremiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joel.
        /// </summary>
        internal static string Joel {
            get {
                return ResourceManager.GetString("Joel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John.
        /// </summary>
        internal static string John {
            get {
                return ResourceManager.GetString("John", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jonah.
        /// </summary>
        internal static string Jonah {
            get {
                return ResourceManager.GetString("Jonah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joshua.
        /// </summary>
        internal static string Joshua {
            get {
                return ResourceManager.GetString("Joshua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jude.
        /// </summary>
        internal static string Jude {
            get {
                return ResourceManager.GetString("Jude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judges.
        /// </summary>
        internal static string Judges {
            get {
                return ResourceManager.GetString("Judges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamentations.
        /// </summary>
        internal static string Lamentations {
            get {
                return ResourceManager.GetString("Lamentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leviticus.
        /// </summary>
        internal static string Leviticus {
            get {
                return ResourceManager.GetString("Leviticus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luke.
        /// </summary>
        internal static string Luke {
            get {
                return ResourceManager.GetString("Luke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malachai.
        /// </summary>
        internal static string Malachai {
            get {
                return ResourceManager.GetString("Malachai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        internal static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matthew.
        /// </summary>
        internal static string Matthew {
            get {
                return ResourceManager.GetString("Matthew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micah.
        /// </summary>
        internal static string Micah {
            get {
                return ResourceManager.GetString("Micah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahum.
        /// </summary>
        internal static string Nahum {
            get {
                return ResourceManager.GetString("Nahum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nehemiah.
        /// </summary>
        internal static string Nehemiah {
            get {
                return ResourceManager.GetString("Nehemiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        internal static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obadaiah.
        /// </summary>
        internal static string Obadaiah {
            get {
                return ResourceManager.GetString("Obadaiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Chronicles.
        /// </summary>
        internal static string OneChronicles {
            get {
                return ResourceManager.GetString("OneChronicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Corinthians.
        /// </summary>
        internal static string OneCorinthians {
            get {
                return ResourceManager.GetString("OneCorinthians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 John.
        /// </summary>
        internal static string OneJohn {
            get {
                return ResourceManager.GetString("OneJohn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Kings.
        /// </summary>
        internal static string OneKings {
            get {
                return ResourceManager.GetString("OneKings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Peter.
        /// </summary>
        internal static string OnePeter {
            get {
                return ResourceManager.GetString("OnePeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Samuel.
        /// </summary>
        internal static string OneSamuel {
            get {
                return ResourceManager.GetString("OneSamuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Thessalonians.
        /// </summary>
        internal static string OneThessalonians {
            get {
                return ResourceManager.GetString("OneThessalonians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Timothy.
        /// </summary>
        internal static string OneTimothy {
            get {
                return ResourceManager.GetString("OneTimothy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philemon.
        /// </summary>
        internal static string Philemon {
            get {
                return ResourceManager.GetString("Philemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippians.
        /// </summary>
        internal static string Philippians {
            get {
                return ResourceManager.GetString("Philippians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proverbs.
        /// </summary>
        internal static string Proverbs {
            get {
                return ResourceManager.GetString("Proverbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psalms.
        /// </summary>
        internal static string Psalms {
            get {
                return ResourceManager.GetString("Psalms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revelation.
        /// </summary>
        internal static string Revelation {
            get {
                return ResourceManager.GetString("Revelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romans.
        /// </summary>
        internal static string Romans {
            get {
                return ResourceManager.GetString("Romans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruth.
        /// </summary>
        internal static string Ruth {
            get {
                return ResourceManager.GetString("Ruth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song of Solomon.
        /// </summary>
        internal static string SongOfSolomon {
            get {
                return ResourceManager.GetString("SongOfSolomon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 John.
        /// </summary>
        internal static string ThreeJohn {
            get {
                return ResourceManager.GetString("ThreeJohn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titus.
        /// </summary>
        internal static string Titus {
            get {
                return ResourceManager.GetString("Titus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Chronicles.
        /// </summary>
        internal static string TwoChronicles {
            get {
                return ResourceManager.GetString("TwoChronicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Corinthians.
        /// </summary>
        internal static string TwoCorinthians {
            get {
                return ResourceManager.GetString("TwoCorinthians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 John.
        /// </summary>
        internal static string TwoJohn {
            get {
                return ResourceManager.GetString("TwoJohn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Kings.
        /// </summary>
        internal static string TwoKings {
            get {
                return ResourceManager.GetString("TwoKings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Peter.
        /// </summary>
        internal static string TwoPeter {
            get {
                return ResourceManager.GetString("TwoPeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Samuel.
        /// </summary>
        internal static string TwoSamuel {
            get {
                return ResourceManager.GetString("TwoSamuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Thessalonians.
        /// </summary>
        internal static string TwoThessalonians {
            get {
                return ResourceManager.GetString("TwoThessalonians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Timothy.
        /// </summary>
        internal static string TwoTimothy {
            get {
                return ResourceManager.GetString("TwoTimothy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zechariah.
        /// </summary>
        internal static string Zechariah {
            get {
                return ResourceManager.GetString("Zechariah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zephaniah.
        /// </summary>
        internal static string Zephaniah {
            get {
                return ResourceManager.GetString("Zephaniah", resourceCulture);
            }
        }
    }
}
